import type { Knex } from "knex";

/**
 * Collections (spec §2.3). The id is generated by the application (32 url-safe random chars)
 * and doubles as the API key; it never changes, reassignment only moves operator_id.
 * */
export async function up(knex: Knex): Promise<void> {
  await knex.schema.createTable("collections", (t) => {
    t.text("id").primary();
    t.uuid("operator_id").notNullable().references("users.id").onDelete("RESTRICT");
    t.text("name").notNullable();
    t.text("schedule_mode").notNullable().defaultTo("after_review");
    t.uuid("provider_id").references("providers.id").onDelete("RESTRICT");
    t.timestamp("created_at", { useTz: true }).notNullable().defaultTo(knex.fn.now());
    t.timestamp("updated_at", { useTz: true }).notNullable().defaultTo(knex.fn.now());

    t.check("schedule_mode in ('after_review', 'immediate')", [], "collections_schedule_mode_check");
    t.unique(["operator_id", "name"]);
    t.index(["provider_id"]);
  });
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.dropTable("collections");
}
